baseURL: "https://nolleh.github.io/"
languageCode: "ko-KR"
title: "The Computer Programmer, Nolleh"
paginate: 5
theme: "PaperMod"
disqusShortname: "nolleh-github-io"
googleAnalytics: "UA-102565363-1"

params:
  author: "nolleh"
  defaultTheme: "auto"
  ShowBreadCrumbs: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
  showtoc: true
keys: ["title", "permalink", "summary", "content"]
menu:
  main: 
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
outputs:
  home:
    - HTML
    - RSS
    - JSON
