baseurl = "https://nolleh.github.io"
languageCode = "ko-KR"
title = "The Computer Programmer, Nolleh"
theme = "hello-programmer"
#theme = "Kraiklyn"
Paginate    = 2                    # the number of posts on a page
disqusShortname = "nolleh-github-io"
googleAnalytics = "UA-102565363-1"

[params]
    author = "nolleh"
    locale = "ko-KR"
    #githubName      = "nolleh"
    #linkedinName    = "https://www.linkedin.com/in/경미-김-a9805a82"

[author]
    name = "nolleh"
    email = "nolleh7707@gmail.com"

#[params]

## hugo-multi-bootswatch
##[params.theme]
##	inverse = true
##	name = "journal"
