baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "The Computer Programmer, Nolleh"
theme = "hugo-multi-bootswatch"

[params]
github      = "https://github.com/nolleh"
linkedin    = "https://www.linkedin.com/in/경미-김-a9805a82"
disqusShortname = "nolleh-github-io"

[params.theme]
	inverse = true
	name = "journal"
